name: release-pdf-on-push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: .
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: './main.pdf'
